local p = require('inklight.palette')

local bold = 'bold'
local italic = 'italic'
local underline = 'underline'
local undercurl = 'undercurl'

local group = require('inklight.semantic_mapping')(p)

return {
    ---- :h highlight-default ----------------------------------
    ColorColumn = { bg = p.bg2 },
    -- Cursor = {},
    -- lCursor = {},
    -- CursorIM = {},
    -- CursorColumn = {},
    CursorLine = { bg = p.bg2 },
    Normal = { fg = p.fg1, bg = p.bg1 }, -- Normal text
    NormalFloat = { bg = p.bg2 }, -- Normal text in floating windows
    FloatBorder = { fg = p.bg3, bg = p.bg1 },
    -- NormalNC = {},
    -- TermCursor = {},
    -- TermCursorNC = {},
    VertSplit = { fg = p.bg3 },
    WinBar = { bg = p.bg1, fg = p.fg1 },
    WinBarNC = { bg = p.bg1, fg = p.fg2 },
    WinSeparator = { fg = p.bg3 },
    LineNr = { bg = p.bg2, fg = p.fg3 },
    CursorLineNr = { bg = p.bg3, fg = p.fg1, style = bold },
    Folded = { fg = p.magenta.fg3, bg = p.bg2 },
    FoldColumn = { bg = p.bg2, fg = p.bg3 },
    CursorLineFold = { bg = p.bg3 },
    SignColumn = { bg = p.bg2, fg = p.bg3 },
    CursorLineSign = { bg = p.bg3 },
    Pmenu = { bg = p.bg2 },
    PmenuSel = { bg = p.bg3 },
    PmenuSbar = { bg = p.bg2 },
    PmenuThumb = { bg = p.bg3 },
    StatusLine = { bg = p.bg2 },
    StatusLineNC = { bg = p.bg2, fg = p.fg2 },
    WildMenu = { bg = p.bg2 },
    TabLine = { bg = p.bg2, fg = p.fg2 },
    TabLineFill = { bg = p.bg2 },
    TabLineSel = { bg = p.bg2 },
    MatchParen = { fg = p.fg1, bg = p.bg3, style = bold },
    Substitute = { bg = p.yellow.bg1 },
    Search = { bg = p.yellow.bg1 },
    CurSearch = { bg = p.yellow.bg2 },
    IncSearch = { bg = p.cyan.bg1 },
    Visual = { bg = p.cyan.bg1 },
    -- VisualNOS = {},
    Conceal = { fg = p.fg2 },
    Whitespace = { fg = p.bg3 },
    EndOfBuffer = { fg = p.bg3 },
    NonText = { fg = p.bg3 },
    SpecialKey = { fg = p.bg3 },
    Directory = { fg = p.magenta.fg1 },
    Title = { fg = p.cyan.fg1 },
    ErrorMsg = { fg = p.bg1, bg = p.red.fg2 },
    ModeMsg = { fg = p.fg2 },
    -- MsgArea = {},
    -- MsgSeparator = {},
    MoreMsg = { fg = p.blue.fg2 },
    WarningMsg = { fg = p.yellow.fg2 },
    Question = { fg = p.green.fg2 },

    ---- :h group-name -----------------------------------------
    Identifier = { fg = group.variable }, -- (preferred) any variable name
    Comment = { fg = group.comment },
    Function = { fg = group.func },
    String = { fg = group.string },
    Character = { fg = group.string },
    Constant = { fg = group.variable },
    Number = { fg = group.constant },
    Float = { fg = group.constant },
    Boolean = { fg = group.constant },
    Operator = { fg = group.text },
    Statement = { fg = group.keyword }, -- (preferred) any statement
    Conditional = { fg = group.keyword }, -- if, then, else, etc.
    Repeat = { fg = group.keyword }, -- for, do, while, etc.
    Exception = { fg = group.keyword }, -- try, catch, throw
    Label = { fg = group.variable },
    -- Keyword = {}, -- any other keyword
    PreProc = { fg = group.annotation }, -- (preferred) generic Preprocessor
    -- Include = {},
    -- Define = {},
    -- Macro = {},
    -- PreCondit = {},
    Type = { fg = group.type },
    -- StorageClass = {},
    -- Structure = {},
    -- Typedef = {},
    Special = { fg = group.text },
    -- SpecialChar = {};
    Tag = { fg = group.text },
    Delimiter = { fg = group.text },
    -- Specialcomment = {};
    -- Debug = {};
    Underlined = { style = underline },
    Bold = { style = bold },
    Italic = { style = italic },
    Ignore = { fg = p.fg2 },
    Error = { bg = p.red.fg1 },
    Todo = { fg = p.yellow.fg1, style = bold },

    ---- :h lsp-semantic_tokens --------------------------------
    ['@lsp.type.annotation.java'] = { fg = group.annotation },
    ['@lsp.type.namespace.rust'] = { fg = group.variable },
    ['@lsp.type.parameter.java'] = { fg = group.variable },
    ['@lsp.typemod.variable.defaultlibrary.javascript'] = { fg = group.text },
    ['@lsp.typemod.variable.defaultlibrary.typescript'] = { fg = group.text },
    ['@lsp.typemod.variable.defaultlibrary.javascriptreact'] = { fg = group.text },
    ['@lsp.typemod.variable.defaultlibrary.typescriptreact'] = { fg = group.text },

    ---- :h nvim-treesitter (external plugin) ------------------
    ['@attribute'] = { fg = group.attribute },
    ['@comment'] = { fg = group.comment },
    ['@constant.javascript'] = { fg = group.variable, style = italic },
    ['@constant.typescript'] = { fg = group.variable, style = italic },
    ['@constant.builtin.go'] = { fg = group.constant },
    ['@constant.builtin.javascript'] = { fg = group.constant },
    ['@constant.builtin.typescript'] = { fg = group.constant },
    ['@constant.builtin.tsx'] = { fg = group.constant },
    ['@constructor'] = { fg = group.func },
    ['@constructor.lua'] = { fg = group.text },
    ['@function'] = { fg = group.func },
    ['@function.macro'] = { fg = group.func },
    ['@function.builtin.go'] = { fg = group.func },
    ['@keyword.operator'] = { fg = group.text },
    ['@keyword.type.go'] = { fg = group.keyword },
    ['@label'] = { fg = group.variable },
    ['@module.elm'] = { fg = group.variable },
    ['@namespace'] = { fg = group.variable },
    ['@parameter'] = { fg = group.variable },
    ['@punctuation.delimiter'] = { fg = group.text },
    ['@punctuation.bracket'] = { fg = group.text },
    ['@punctuation.special'] = { fg = group.text },
    ['@string.regexp'] = { fg = group.constant },
    ['@string.escape'] = { fg = group.constant },
    ['@type.builtin'] = { fg = group.type },
    ['@type.qualifier'] = { fg = group.type },
    ['@variable'] = { fg = p.fg1 },
    ['@variable.builtin'] = { fg = group.text },
    ['@tag'] = { fg = group.type },
    ['@tag.attribute'] = { fg = group.attribute },
    ['@tag.builtin'] = { fg = group.type },
    ['@tag.delimiter'] = { fg = group.text },
    ['@tag.javascript'] = { fg = group.func },
    ['@tag.tsx'] = { fg = group.func },
    ['@text'] = { fg = p.fg1 },
    ['@text.title'] = { fg = p.cyan.fg1 },
    ['@text.warning'] = { fg = p.red.fg2 },
    markdownH1 = { fg = p.magenta.fg1 },
    markdownH2 = { fg = p.magenta.fg1 },
    markdownH3 = { fg = p.magenta.fg1 },
    markdownH4 = { fg = p.magenta.fg1 },
    markdownLink = { fg = p.blue.fg1 },
    markdownListMarker = { fg = p.magenta.fg2 },
    markdownUrl = { fg = p.blue.fg1 },
    zshFunction = { fg = group.func },

    ---- :h spell ----------------------------------------------
    SpellBad = { sp = p.red.fg2, style = undercurl },
    SpellCap = { sp = p.red.fg2, style = undercurl },
    SpellLocal = { sp = p.red.fg2, style = undercurl },
    SpellRare = { sp = p.yellow.fg2, style = undercurl },

    ---- :h diff ----------------------------------------------
    DiffAdd = { bg = p.green.bg1 },
    DiffChange = { bg = p.yellow.bg1 },
    DiffDelete = { bg = p.red.bg1 },
    DiffText = { bg = p.yellow.bg2 },

    ---- :h diagnostic-highlight -------------------------------
    DiagnosticError = { fg = p.red.fg2 },
    DiagnosticWarn = { fg = p.yellow.fg2 },
    DiagnosticHint = { fg = p.cyan.fg2 },
    DiagnosticInfo = { fg = p.blue.fg2 },
    DiagnosticUnnecessary = { fg = p.fg3 },

    DiagnosticVirtualTextError = { fg = p.red.fg2 },
    DiagnosticVirtualTextWarn = { fg = p.yellow.fg2 },
    DiagnosticVirtualTextHint = { fg = p.cyan.fg2 },
    DiagnosticVirtualTextInfo = { fg = p.blue.fg2 },

    DiagnosticUnderlineError = { sp = p.red.fg2, style = undercurl },
    DiagnosticUnderlineWarn = { sp = p.yellow.fg2, style = undercurl },
    DiagnosticUnderlineHint = { sp = p.cyan.fg2, style = undercurl },
    DiagnosticUnderlineInfo = { sp = p.blue.fg2, style = undercurl },

    -- DiagnosticFloatingError = {},
    -- DiagnosticFloatingWarn = {},
    -- DiagnosticFloatingHint = {},
    -- DiagnosticFloatingInfo = {},

    -- DiagnosticSignError = {},
    -- DiagnosticSignWarn = {},
    -- DiagnosticSignHint = {},
    -- DiagnosticSignInfo = {},

    ---- :h lsp-highlight --------------------------------------
    LspInlayHint = { fg = p.fg3 },
    LspReferenceText = { bg = p.bg3 },
    LspReferenceRead = { bg = p.bg3 },
    LspReferenceWrite = { bg = p.bg3 },

    LspDiagnosticsDefaultError = { fg = p.red.fg2 },
    LspDiagnosticsDefaultWarning = { fg = p.yellow.fg2 },
    LspDiagnosticsDefaultHint = { fg = p.cyan.fg2 },
    LspDiagnosticsDefaultInformation = { fg = p.blue.fg2 },

    -- LspDiagnosticsVirtualTextError = {},
    -- LspDiagnosticsVirtualTextWarning = {},
    -- LspDiagnosticsVirtualTextHint = {},
    -- LspDiagnosticsVirtualTextInformation = {},

    LspDiagnosticsUnderlineError = { style = undercurl },
    LspDiagnosticsUnderlineWarning = { style = undercurl },
    LspDiagnosticsUnderlineHint = { style = undercurl },
    LspDiagnosticsUnderlineInformation = { style = undercurl },

    -- LspDiagnosticsFloatingError = {},
    -- LspDiagnosticsFloatingWarning = {},
    -- LspDiagnosticsFloatingHint = {},
    -- LspDiagnosticsFloatingInformation = {},

    -- LspDiagnosticsSignError = {},
    -- LspDiagnosticsSignWarning = {},
    -- LspDiagnosticsSignHint = {},
    -- LspDiagnosticsSignInformation = {},

    ---- EXTERNAL PLUGINS --------------------------------------

    -- fzf-lua
    FzfLuaNormal = { fg = p.fg1, bg = p.bg1 },
    FzfLuaBorder = { fg = p.bg3, bg = p.bg1 },
    FzfLuaTitle = { fg = p.bg1, bg = p.cyan.fg1 },
    FzfLuaTitleFlags = { fg = p.magenta.fg2, bg = p.bg1 },
    FzfLuaBackdrop = { bg = p.fg3 },
    FzfLuaPreviewTitle = { fg = p.bg1, bg = p.magenta.fg1 },
    FzfLuaHeaderBind = { fg = p.magenta.fg2, bg = p.bg2 },
    FzfLuaHeaderText = { fg = p.fg2 },
    FzfLuaPathColNr = { fg = p.blue.fg2 },
    FzfLuaPathLineNr = { fg = p.blue.fg1 },
    FzfLuaBufName = { fg = p.magenta.fg1 },
    FzfLuaBufId = { fg = p.magenta.fg1 },
    FzfLuaBufNr = { fg = p.magenta.fg1 },
    FzfLuaBufFlagCur = { fg = p.fg1 },
    FzfLuaBufFlagAlt = { fg = p.fg2 },
    FzfLuaTabTitle = { fg = p.bg1, bg = p.yellow.fg1 },
    FzfLuaTabMarker = { fg = p.magenta.fg2 },
    FzfLuaDirPart = { fg = p.purple.fg1 },
    FzfLuaFilePart = { fg = p.purple.fg1 },
    FzfLuaLivePrompt = { fg = p.fg1 },
    FzfLuaLiveSym = { fg = p.green.fg1 },
    FzfLuaCmdEx = { fg = p.cyan.fg1 },
    FzfLuaCmdBuf = { fg = p.cyan.fg1 },
    FzfLuaCmdGlobal = { fg = p.cyan.fg1 },
    FzfLuaFzfMatch = { fg = p.green.fg1 },
    FzfLuaFzfScrollbar = { fg = p.magenta.fg3 },
    FzfLuaFzfGutter = { bg = p.bg2 },
    FzfLuaFzfInfo = { fg = p.fg2 },
    FzfLuaFzfPointer = { fg = p.magenta.fg2 },
    FzfLuaFzfPrompt = { fg = p.fg1 },
    FzfLuaFzfQuery = { fg = p.fg1 },

    -- :h gitsigns
    GitSignsAdd = { fg = p.green.fg2 },
    GitSignsChange = { fg = p.green.fg2 },
    GitSignsDelete = { fg = p.red.fg2 },
    GitSignsCurrentLineBlame = { fg = p.fg3 },

    -- neotest
    NeotestAdapterName = { fg = p.fg1 },
    NeotestDir = { fg = p.fg1 },
    NeotestRunning = { fg = p.green.fg2 },
    NeotestPassed = { fg = p.green.fg1 },
    NeotestFailed = { fg = p.red.fg2 },
    NeotestSkipped = { fg = p.yellow.fg2 },
    NeotestTest = { fg = p.fg1 },
    NeotestFile = { fg = p.fg1 },
    NeotestNamespace = { fg = p.fg1 },
    NeotestFocused = { fg = p.magenta.fg1 },
    NeotestIndent = { fg = p.fg3 },
    NeotestMarked = { fg = p.blue.fg1 },
    NeotestWinSelect = { fg = p.cyan.fg1 },
    NeotestTarget = { fg = p.cyan.fg1 },
    NeotestUnknown = { fg = p.fg2 },
    NeotestExpandMarker = { fg = p.fg3 },

    -- nvim-cmp
    CmpItemAbbrMatch = { fg = p.green.fg1 },
    CmpItemAbbrMatchFuzzy = { fg = p.green.fg2 },
    CmpItemKindMenu = { fg = p.green.fg1 },
    CmpItemKindText = { fg = group.text },
    CmpItemKindKeyword = { fg = group.keyword },
    CmpItemKindVariable = { fg = group.variable },
    CmpItemKindValue = { fg = group.text },
    CmpItemKindConstant = { fg = group.constant },
    CmpItemKindOperator = { fg = group.text },
    CmpItemKindFunction = { fg = group.func },
    CmpItemKindMethod = { fg = group.func },
    CmpItemKindReference = { fg = group.text },
    CmpItemKindClass = { fg = group.type },
    CmpItemKindInterface = { fg = group.type },
    CmpItemKindStruct = { fg = group.type },
    CmpItemKindFolder = { fg = p.fg1 },
    CmpItemKindFile = { fg = p.fg1 },

    -- nvim-dap
    DapBreakpointText = { fg = p.red.fg2 },
    DapBreakpointRejectedText = { fg = p.blue.fg2 },
    DapStoppedLine = { bg = p.blue.bg1 },
    DapStoppedText = { fg = p.blue.fg1 },

    -- :h nvim-dap-ui
    DapUIScope = { fg = p.cyan.fg1 },
    DapUIType = { fg = p.blue.fg1 },
    DapUIModifiedValue = { fg = p.green.fg1, style = bold },
    DapUIDecoration = { fg = p.cyan.fg1 },
    DapUIThread = { fg = p.magenta.fg1 },
    DapUIStoppedThread = { fg = p.magenta.fg3 },
    DapUISource = { fg = p.yellow.fg1 },
    DapUILineNumber = { fg = p.magenta.fg2 },
    DapUIFloatBorder = { fg = p.bg3 },
    DapUIWatchesEmpty = { fg = p.fg3 },
    DapUIWatchesValue = { fg = p.green.fg1 },
    DapUIWatchesError = { fg = p.red.fg2 },
    DapUIBreakpointsPath = { fg = p.blue.fg1 },
    DapUIBreakpointsInfo = { fg = p.blue.fg2 },
    DapUIBreakpointsCurrentLine = { fg = p.cyan.fg1 },
    DapUIPlayPause = { fg = p.green.fg1 },
    DapUIRestart = { fg = p.green.fg2 },
    DapUIStop = { fg = p.red.fg1 },
    DapUIStepOver = { fg = p.fg1 },
    DapUIStepInto = { fg = p.fg1 },
    DapUIStepBack = { fg = p.fg1 },
    DapUIStepOut = { fg = p.fg1 },
    DapUIUnavailable = { fg = p.fg3 },

    -- nvim-dap-virtual-text
    NvimDapVirtualText = { fg = p.fg3 },

    -- :h nvim-tree
    NvimTreeRootFolder = { fg = p.cyan.fg1 },
    NvimTreeFolderName = { fg = p.fg1 },
    NvimTreeOpenedFolderName = { fg = p.fg1 },
    NvimTreeExecFile = { fg = p.blue.fg1 },
    NvimTreeSpecialFile = { fg = p.magenta.fg1 },
    NvimTreeGitDirty = { fg = p.red.fg1 },
    NvimTreeGitNew = { fg = p.green.fg1 },
    NvimTreeGitRenamed = { fg = p.green.fg1 },
    NvimTreeGitStaged = { fg = p.green.fg1 },
    NvimTreeWindowPicker = { fg = p.bg1, bg = p.cyan.fg1 },

    -- :h telescope
    TelescopeBorder = { fg = p.fg3, bg = p.bg1 },
    TelescopeNormal = { bg = p.bg1 },
    TelescopePromptTitle = { fg = p.bg1, bg = p.cyan.fg1 },
    TelescopePromptBorder = { fg = p.fg3, bg = p.bg1 },
    TelescopePromptCounter = { fg = p.fg1 },
    TelescopePromptNormal = { fg = p.fg1 },
    TelescopePromptPrefix = { fg = p.fg1 },
    TelescopeResultsTitle = { fg = p.bg1, bg = p.magenta.fg1 },
    TelescopePreviewTitle = { fg = p.bg1, bg = p.yellow.fg1 },
    TelescopePreviewBorder = { fg = p.fg3, bg = p.bg1 },
    TelescopePreviewNormal = { bg = p.bg1 },
    TelescopeSelection = { bg = p.bg3 },
    TelescopeMatching = { fg = p.green.fg1 },

    -- snacks
    SnacksIndent = { fg = p.bg3 },
    SnacksIndentScope = { fg = p.magenta.fg3 },

    -- :h sneak
    Sneak = { bg = p.yellow.bg1 },
    SneakCurrent = { bg = p.yellow.bg2 },
    SneakScope = { bg = p.cyan.bg1 },
    SneakLabel = { fg = p.fg1, bg = p.yellow.bg1, style = bold },

    -- vim-illuminate
    IlluminatedWordText = { bg = p.bg3 },
    IlluminatedWordRead = { bg = p.bg3 },
    IlluminatedWordWrite = { bg = p.bg3 },
}
